### ISSUE TITLE
error for: 'com.android.tools.build:gradle:4.0.0'

### ISSUE THREAD

**Issue by 3HJack** [novoda/bintray-release#317] opened 2020-05-29 09:52 UTC
Unable to load class 'org.gradle.api.internal.java.usagecontext.LazyConfigurationUsageContext'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by smpeters** [comment] 2020-05-29 16:45
This is a duplicate of #298

**Comment by panpf** [comment] 2020-09-11 07:38
I have modified some codes on the basis of this library to support Gradle 6.0+ and Android Gradle Plugin 4.0+, and then released a brand new library, you can try to see if it can solve your problem, https://github.com/panpf/bintray-publish

**Closed** 2022-02-11 06:02 UTC
