### ISSUE TITLE
用的 classpath 'com.novoda:bintray-release:0.9.1'报错如下

### ISSUE THREAD

**Issue by 214024475** [novoda/bintray-release#288] opened 2019-07-01 02:08 UTC
WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: tracker_pgy

**Comment by mr-archano** [comment] 2019-07-02 22:58
Thanks for the interest. This issue is a duplicate of #260.

**Closed by mr-archano** 2019-07-02 22:58 UTC
