### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

### ISSUE THREAD

**Issue by qsxiaogang** [novoda/bintray-release#88] opened 2016-05-31 14:52 UTC
What went wrong:
Execution failed for task ':common:bintrayUpload'.

> javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

I got this error at last step. I have try to look about the error form google,but no solution.

Can you supply any suggestion ?

**Comment by iFarSeer** [comment] 2016-07-06 05:49
+1

**Comment by wangzhiyuan** [comment] 2016-08-17 10:29
+2

**Comment by ouchadam** [comment] 2016-08-17 13:05
this seems quite odd 😿 , are you using a vpn? Is the bintray website certified for you?

<img width="213" alt="screen shot 2016-08-17 at 14 02 19" src="https://cloud.githubusercontent.com/assets/1848238/17737126/5556343c-6483-11e6-9f75-fd1046dd4b52.png">

**Comment by blundell** [comment] 2017-10-31 16:23
no answer to the question posed in over a year - closing as can't reproduce

**Closed by blundell** 2017-10-31 16:23 UTC
