### ISSUE TITLE
Gradle 4.6 and  bintray-release:0.7.0

### ISSUE THREAD

**Issue by wave-chtj** [novoda/bintray-release#245] opened 2018-10-31 03:29 UTC
my project is conflict with gradle-4.6-all.zip  and  bintray-release:0.7.0
so, you can help Solve this Exception?

**Comment by yshrsmz** [comment] 2018-11-02 08:42
looks like a dupe of #177?

**Comment by wave-chtj** [comment] 2018-11-02 09:02
@yshrsmz thank you for your answer. I have already solved it.

**Closed** 2018-11-03 07:36 UTC
