### ISSUE TITLE
INFO: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.

### ISSUE THREAD

**Issue by 908657085** [novoda/bintray-release#295] opened 2019-10-08 09:29 UTC
INFO: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.

    private static def androidArchivePath(LibraryVariant variant) {
        return variant.outputs[0].packageLibraryProvider
    }

**Comment by mr-archano** [comment] 2019-11-28 18:04
Duplicate of #260. Please in future be a good GitHub citizen and check whether the same issue has been raised before filing a new one. Thanks :bowing_man:

**Closed by mr-archano** 2019-11-28 18:04 UTC
